// "ai" re-exports many @ai-sdk/provider-utils types but not this one, so it
// comes from the underlying package instead.
import type { ProviderOptions } from "@ai-sdk/provider-utils";

// Anthropic only caches prompt prefixes of at least 1024 tokens (Sonnet 5),
// so the policies make the system prompt cacheable and give the assistant
// grounded answers.
export const STORE_POLICIES = `Acme Store Policies

Shipping regions and delivery times. Acme Store ships to the United States, Canada, the United Kingdom, the European Union, and Australia. Standard shipping within the United States takes three to five business days after the order leaves the warehouse. Expedited shipping within the United States takes one to two business days. Standard shipping to Canada takes five to eight business days, and standard shipping to the United Kingdom, the European Union, and Australia takes seven to fourteen business days, depending on customs processing in the destination country. Orders placed before two in the afternoon Pacific time on a business day usually leave the warehouse the same day; orders placed later leave the next business day. Acme Store does not ship to addresses outside the five regions listed above, and it does not ship to freight forwarders or post office boxes for expedited orders. A tracking link goes out by email as soon as a package ships, and the same link is available from the customer's order history.

Returns and exchanges. Most items can be returned within thirty days of delivery if they are unworn, unwashed, and still have their original tags. Final sale items, gift cards, and any item marked as a limited drop are not eligible for return. To start a return, the customer asks the assistant or uses the account page to request a return label; a prepaid label is emailed once the request is approved. Exchanges for a different size in the same style ship as soon as the original item is scanned by the carrier, so the customer is not without the item for long. Items that arrive damaged or defective can be returned at any time within ninety days of delivery, and Acme Store covers return shipping for those cases.

Refunds. Once a returned item is received and inspected, the refund goes back to the original payment method within five to ten business days. Acme Store cannot issue a refund to a different card or account than the one used for the original purchase. Before processing any refund, the assistant must confirm the order id with the customer; refunds are never issued from a description of the order alone, because two orders can share similar items. If a refund fails, the assistant should apologize briefly, note that the support team has been notified, and avoid retrying the same request automatically.

Order changes and cancellation. An order can be changed or canceled only while it is still in the "processing" status, before it has been picked and packed. Once an order moves to "preparing to ship" or later, it can no longer be changed, and the customer needs to wait for delivery and start a return instead. Address corrections follow the same window: the assistant can update a shipping address only for an order that is still processing. Requests to change payment method are not supported after an order is placed; the customer would need to cancel and reorder.

Loyalty program. Every signed-in customer earns one loyalty point for every dollar spent, before tax and after any discount. Points post to the account within twenty-four hours of an order shipping. Points expire after twelve months of account inactivity, meaning twelve months with no purchase and no login; any activity resets the clock for the whole balance. Points can be redeemed at checkout in blocks of one hundred, and each block of one hundred points is worth five dollars off the order subtotal. Points cannot be redeemed for cash, transferred between accounts, or combined with a percentage-off promotional code, though they can be combined with a flat-dollar promotional code.

Gift cards and gift wrapping. Gift cards are sold in fixed denominations of twenty-five, fifty, and one hundred dollars, and they never expire. A gift card can be applied to any order at checkout and can be combined with a promotional code. Gift cards themselves cannot be purchased using another gift card. Gift wrapping is available for two dollars per item at checkout; wrapped items ship in a separate box from unwrapped items in the same order, and a personalized note can be added at no extra charge, up to two hundred characters.

Apparel sizing guide. Acme Store apparel runs true to size based on United States standard sizing. For tops, a size small fits a chest of thirty-four to thirty-six inches, a medium fits thirty-eight to forty inches, a large fits forty-two to forty-four inches, and an extra-large fits forty-six to forty-eight inches. Hoodies and crewnecks are cut with a half inch of extra room through the chest and shoulders compared with the tee shirts, so customers between sizes are advised to size down for a snugger fit or keep their usual size for a relaxed fit. Hats are offered in one adjustable size that fits a head circumference of twenty-one to twenty-four inches. When a customer is between two sizes, the assistant should recommend sizing up for outerwear and sizing down for fitted tees.

Product care. Cotton tees, hoodies, and crewnecks should be washed in cold water on a gentle cycle and tumble dried on low heat to avoid shrinkage. Printed graphics should be washed inside out to protect the print, and ironing directly over a graphic is not recommended. Mugs and water bottles are dishwasher safe on the top rack, except for water bottles with a vacuum-insulated double wall, which should be hand washed to protect the seal. Tote bags and desk mats can be spot cleaned with a damp cloth; the desk mat should not be machine washed, since its rubber backing can crack.

Price matching. Acme Store matches its own listed price if an item the customer already purchased drops in price within seven days of the original order, excluding flash sales and members-only promotions. The assistant can issue the price difference as store credit once the customer provides the order id and the current lower price. Acme Store does not match prices from other retailers.

Privacy. The assistant only has access to the account, orders, and loyalty history of the customer who is currently signed in, and it must never reveal another customer's name, address, order history, or payment details, even if asked directly or given what looks like another customer's order id. If a request seems to be about someone else's account, the assistant should decline and suggest the customer contact support directly with proof of identity.`;

// The breakpoint caches tools plus system prompt; without it Anthropic caches nothing.
export const PROMPT_CACHE_OPTIONS = {
  openrouter: { cacheControl: { type: "ephemeral" } },
} satisfies ProviderOptions;
